// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRTDg0xyW2NDCBmyDYae39O54Iv73Yksk',
    appId: '1:750464718466:web:fba0025b72ca1c5a3ac69b',
    messagingSenderId: '750464718466',
    projectId: 'innoclassroom',
    authDomain: 'innoclassroom.firebaseapp.com',
    databaseURL: 'https://innoclassroom-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'innoclassroom.firebasestorage.app',
    measurementId: 'G-KJ4MG766SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTBiv374Qjo5pKronQK9SVAEZTH9qH3EQ',
    appId: '1:750464718466:android:4b189c4ff925d5a73ac69b',
    messagingSenderId: '750464718466',
    projectId: 'innoclassroom',
    databaseURL: 'https://innoclassroom-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'innoclassroom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqOqGexLuNdKEpAMuofhc1t-avFUAVDWc',
    appId: '1:750464718466:ios:03f956d9000973dd3ac69b',
    messagingSenderId: '750464718466',
    projectId: 'innoclassroom',
    databaseURL: 'https://innoclassroom-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'innoclassroom.firebasestorage.app',
    iosBundleId: 'com.example.pinoyTrivia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqOqGexLuNdKEpAMuofhc1t-avFUAVDWc',
    appId: '1:750464718466:ios:03f956d9000973dd3ac69b',
    messagingSenderId: '750464718466',
    projectId: 'innoclassroom',
    databaseURL: 'https://innoclassroom-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'innoclassroom.firebasestorage.app',
    iosBundleId: 'com.example.pinoyTrivia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRTDg0xyW2NDCBmyDYae39O54Iv73Yksk',
    appId: '1:750464718466:web:412d510b6e4a8dc03ac69b',
    messagingSenderId: '750464718466',
    projectId: 'innoclassroom',
    authDomain: 'innoclassroom.firebaseapp.com',
    databaseURL: 'https://innoclassroom-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'innoclassroom.firebasestorage.app',
    measurementId: 'G-TDWHB0Q7DR',
  );
}
